site_name: My Projects
site_author: Mateusz Chmielarz
site_description: >-
    My Data Science Portfolio


repo_name: MrPejper/ds_ai_portfolio
repo_url: https://github.com/MrPejper/ds_ai_portfolio

theme:
  name: material

nav:
- Home Page: index.md
- Data Analysis:
  - "Iris": iris/index.md
  - "Titanic": titanic/index.md
  - "Supplements": supplements/index.md
- Applications:
  - "Most_important_variables": variables/index.md
  - "Diabetes": diabetes/index.md
  

 
