site_name: Moje projekty
site_author: Mateusz Chmielarz
site_description: >-
    Portfolio moich projektów z Data Science.


repo_name: MrPejper/ds_ai_portfolio
repo_url: https://github.com/MrPejper/ds_ai_portfolio

theme:
  name: material

nav:
- Strona Domowa: index.md
- Analizy danych:
  - "Iris": iris/index.md
  - "Titanic": titanic/index.md
  - "Suplementy": supplements/index.md
- Aplikacje:
  - "Najważniejsze zmienne": variables/index.md
  - "Cukrzyca": diabetes/index.md
  

 
